name: Build and publish xk6-mongo

on:
  push:
    tags:
      - "v*"
jobs:
  build:
    name: Build xk6-mongo
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ðŸ›Žï¸
        uses: actions/checkout@v3
        with:
          fetch-depth: -1

      - name: Build ðŸ—ï¸
        id: build
        uses: szkiba/xk6bundler@v0
        with:
          platform: linux/amd64 windows/amd64 darwin/amd64
          with: |
            github.com/GhMartingit/xk6-mongo@${{ github.ref_name }}
            
      - name: Install Go ðŸ§‘â€ðŸ’»
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
        uses: actions/setup-go@v3
        with:
          go-version: '1.22'

      - name: Generate dependencies list
        run: go list -m all > go.list

      - name: Install SPDX tool
        run: go install github.com/spdx/tools-golang/bom/cmd/rdf2v1@latest


      - name: Generate SBOM
        run: rdf2v1 -format tagvalue go.list > sbom.spdx

      - name: Upload SPDX SBOM artifact for go.mod ðŸ’¾
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
        uses: actions/upload-artifact@v3
        with:
          name: sbom.spdx
          path: sbom.spdx

      - name: Create Release ðŸ“¦
        uses: softprops/action-gh-release@v1
        with:
          files: dist/*.tar.gz